config/routes.rb
Rails.application.routes.draw do
   resources :qr_codes, only: [:new, :create]
   root to: "qr_codes#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  def new
  end

  def create
    @qr = RQRCode::QRCode.new(qr_code_params[:text], size: 4)
  end

  private
  def qr_code_params
    params.require(:qr_code).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QRCodeRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qr_codes/create.html.erb
<table class="qr-code">
<% @qr.modules.each_index do |x| %>
  <tr>
  <% @qr.modules.each_index do |y| %>
   <% if @qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
<br />
<br />
<%= link_to "New QR Code", new_qr_code_path %>

app/views/qr_codes/new.html.erb
<h1>Create QRCode With Text</h1>
<%= form_for :qr_code, url: qr_codes_path do |f| %>
  <%= f.label :text  %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>